
path: '/content/gdrive/My Drive/person_detector/my_dataset_yolo' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
test: images/val  # val images (relative to 'path')

# Classes
names:
  0: person
